# Generated by Django 3.2.7 on 2021-09-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_google', models.IntegerField()),
                ('task', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('img_task', models.CharField(blank=True, max_length=255, null=True)),
                ('img_solution', models.CharField(blank=True, max_length=255, null=True)),
                ('id_orig', models.IntegerField(blank=True, null=True)),
                ('date_using', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'set',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trajectory',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.category')),
                ('id_theme', models.ForeignKey(db_column='id_theme', on_delete=django.db.models.deletion.CASCADE, to='problems.theme')),
            ],
            options={
                'db_table': 'theme_category',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_trajectory', models.ForeignKey(blank=True, db_column='id_trajectory', null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.trajectory')),
            ],
            options={
                'db_table': 'syllabus',
            },
        ),
        migrations.CreateModel(
            name='SetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_task', models.IntegerField()),
                ('criteries', models.TextField(blank=True, null=True)),
                ('id_set', models.ForeignKey(db_column='id_set', on_delete=django.db.models.deletion.CASCADE, to='problems.set')),
                ('id_task', models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'db_table': 'set_task',
            },
        ),
        migrations.AddField(
            model_name='set',
            name='id_syllabus',
            field=models.ForeignKey(blank=True, db_column='id_syllabus', null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.syllabus'),
        ),
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('id_theme_cat', models.ForeignKey(db_column='id_theme_cat', on_delete=django.db.models.deletion.CASCADE, to='problems.themecategory')),
            ],
            options={
                'db_table': 'problem_category',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='id_type',
            field=models.ForeignKey(blank=True, db_column='id_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.type'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=63)),
                ('date', models.TimeField()),
                ('description', models.TextField()),
                ('id_set_task', models.ForeignKey(db_column='id_set_task', on_delete=django.db.models.deletion.CASCADE, to='problems.settask')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
