# Generated by Django 3.2.7 on 2021-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='enum_set',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
