# Generated by Django 3.2.7 on 2021-10-05 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0003_cart_carttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carttask',
            name='id_cart',
            field=models.ForeignKey(db_column='id_cart', on_delete=django.db.models.deletion.CASCADE, to='problems.cart'),
        ),
    ]
